language: android
components:
- tools
- platform-tools
- build-tools-26.0.0
- platform-tools
- android-26
- extra-android-m2repository
licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
script:
- ./gradlew build connectedCheck
